platform :ios, '7.0'
pod 'QULibrary', :path => '/Users/allran/Desktop/apple/APP/Allran/QULibrary'

pod 'AFNetworking'
pod 'SVProgressHUD'
pod 'Masonry'
pod 'IQKeyboardManager'
pod 'LKDBHelper',:head
pod 'MJExtension'
pod 'MJRefresh'
